### ISSUE TITLE
node 12, npm 2

### ISSUE THREAD

**Issue by omgbox** [ItzBlitz98/torrentflix#12] opened 2015-03-23 17:04 UTC
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn peerflix ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

**Comment by ItzBlitz98** [comment] 2015-03-23 17:11
Going to ask the obvious question first, Do you have peerflix installed ?

**Comment by omgbox** [comment] 2015-03-24 00:04
yes, when i select number, it starts peerflix but soon afterwards it stops peerflix

> open vlc and enter http://192.168.2.3:8888/ as the network address
> 
> info streaming The.Bleach.Movie.4.-.The.Hell.Verse.2010.Jap.AC3.480p.DVDRip.DivX.AF4P.avi (1.6GB) - 0.0/s from 0/0 peers  
> info path /tmp/torrent-stream/e2b12ad324b4b6f49a383b437eeef2abc37abc40
> info downloaded 0.0 and uploaded 0.0 in 0s with 0 hotswaps  
> info verified 0 pieces and received 0 invalid pieces
> info peer queue size is 0

**Comment by omgbox** [comment] 2015-03-24 00:05
> torrentflix
> ? What torrent site do you want to search? Rarbg
> ? Search for a torrent:  bleach movie 4
> Searching for bleach movie 4
> 1) Frankenstein.2007.DVDRip.XviD-VoMiT 696.78 MB 1 0
> 2) [DB] Bleach Movie 1 HD 1440x768 [2C434BF0] 2.73 GB 1 0
> 3) Frankenstein.2007.WS.PDTV.XviD-REMAX 699.90 MB 1 1
> 4) [IceFanSubs] Bleach Movie 4 Hell Chapter (848x480 h264 BG) 1.48 GB 1 1
> 5) [IceFanSubs] Bleach Movie 3 - Fade to Black [BG] [848x480 AVC AAC] 775.07 MB 1 0
> 6) [ASAF] Bleach - Movie 3 - Fade to Black  [1280x720,H264+MP3] 934.52 MB 1 1
> 7) Bleach.Hell.Verse.2010.BDRip.XviD-RedBlade 705.00 MB 1 0
> ? Torrent to stream (eg. 1, 2, 3..) or (b)ack or (e)xit:  4
> Streaming [IceFanSubs] Bleach Movie 4 Hell Chapter (848x480 h264 BG)
> /usr/local/lib/node_modules/torrentflix/lib/torrent_parse.js:20
>         if(typeof torrent.files !== undefined){
>                          ^
> TypeError: Cannot read property 'files' of undefined
>     at /usr/local/lib/node_modules/torrentflix/lib/torrent_parse.js:20:26
>     at /usr/local/lib/node_modules/torrentflix/node_modules/read-torrent/index.js:18:13
>     at process._tickCallback (node.js:355:11)

**Comment by ItzBlitz98** [comment] 2015-03-24 01:39
Looks like the rarbg scraper is broken will try to fix it.

Is the error you encounter rarbg specific or do the other sites do it as well ?

**Comment by ItzBlitz98** [comment] 2015-03-24 17:05
This should now be fixed in e53247f34c8d930c0736c25f82318a9ad15612df.
If you could test it to make sure i would greatly appreciate it :+1:

**Comment by omgbox** [comment] 2015-03-26 19:28
yes still doing it,  it is doing it on every search engine , just about to start it cuts out. 

have you seen new torrent search engine

> https://getstrike.net/torrents/ 
> api https://getstrike.net/api/

elementaryOS 12.04 x86 
npm -v 2.5.1
node -v v0.12.1
tflix -v 6.0.0

> root@nodejs-laptop:~/Downloads/torrentflix/bin# node torrentflix
> ? What torrent site do you want to search? Nyaa
> ? Search for a torrent:  naruto
> Searching for naruto
> 
> ? Torrent to stream (eg. 1, 2, 3..) or (b)ack or (e)xit:  74
> Streaming [HorribleSubs] Naruto Shippuuden - 383 [720p].mkv
> 
> open vlc and enter http://192.168.2.3:8888/ as the network address
> 
> info streaming [HorribleSubs] Naruto Shippuuden - 383 [720p].mkv (315.5MB) - 0.0/s from 0/0 peers  
> info path /tmp/torrent-stream/853f478e72718dc2efa2a3e151a3ff224e0f3f7b
> info downloaded 0.0 and uploaded 0.0 in 0s with 0 hotswaps  
> info verified 0 pieces and received 0 invalid pieces
> info peer queue size is 55
> 
> root@nodejs-laptop:~/Downloads/torrentflix/bin#

**Comment by walidsa3d** [comment] 2015-03-26 19:31
it works well for me

**Comment by omgbox** [comment] 2015-03-26 19:33
might be my node install screwed up :-1:  will reinstall again

**Comment by ItzBlitz98** [comment] 2015-03-26 19:39
I can't seem to reproduce this and i don't know what could be happening since there is no error message to help.

Have you tried streaming something with peerflix on its own too see if its peerflix doing it ?

Also thanks for the suggestion about getstrike.net, Thats a pretty great find :+1:

**Comment by omgbox** [comment] 2015-03-26 19:50
seems to be working on another computer, conclusion my install is messed up. sorry for the trouble.

**Comment by ItzBlitz98** [comment] 2015-03-26 19:53
No worries happy to try to help.

**Closed as completed** 2015-03-27 19:25 UTC
