### ISSUE TITLE
peerflix won't start: ENAMETOOLONG

### ISSUE THREAD

**Issue by zosiu** [ItzBlitz98/torrentflix#33] opened 2015-11-29 00:31 UTC
I'm experiencing this since 8.6.0 (8.5.3 works fine), peerflix won't start, the console says:

```
Streaming [filename]
ENAMETOOLONG, open '""magnet:?MAGNET_THINGS""'
```

Those double quotes look quite suspicious...
I'm on lubuntu 14.04 with npm 3.3.4.

**Comment by ItzBlitz98** [comment] 2015-12-02 01:10
Yea i added those for windows support apologies it broke something else. Will work on a fix.

**Comment by ItzBlitz98** [comment] 2015-12-05 03:04
Ok i have tweaked the windows fix to only apply to windows, This should fix your problem if you could test it as i can't reproduce it that would be a huge help :+1:

**Comment by zosiu** [comment] 2015-12-05 13:40
Seems to be working nicely @ItzBlitz98 , thanks for the fix! :+1:

**Comment by ItzBlitz98** [comment] 2015-12-05 15:36
No problem will close this :smile:

**Closed as completed by ItzBlitz98** 2015-12-05 15:36 UTC
